Import('env')

from glob import glob

all_sources = [ "Cpsfile.cpp",
                "Decode.cpp",
                "Icnfile.cpp",
                "Inifile.cpp",
                "Pakfile.cpp",
                "Shpfile.cpp",
                "Wsafile.cpp",
                "Palette.cpp",
                "Animation.cpp",
                "Stringfile.cpp",
                "Vocfile.cpp",
              ]

libnostalgia = env.Program("../libnostalgia.so", all_sources)
#pakview = env.Program("../pakview", ["pakview.cpp"] + pakview_sources + gui_sources + pak_sources )

Default(libnostalgia)
#Default(pakview)

