import sys
Import('env')

from glob import glob

all_sources = [ "Cpsfile.cpp",
                "Decode.cpp",
                "Icnfile.cpp",
                "Inifile.cpp",
                "Pakfile.cpp",
                "Shpfile.cpp",
                "Wsafile.cpp",
                "Palette.cpp",
                "Animation.cpp",
                "Stringfile.cpp",
                "Vocfile.cpp",
		"Font.cpp"
              ]

libeastwood = env.SharedLibrary(target='../libeastwood.so', source=all_sources)

Return('libeastwood')

