import sys
Import('env')

from glob import glob

all_sources = [ "CpsFile.cpp",
                "Decode.cpp",
                "IcnFile.cpp",
                "IniFile.cpp",
                "PakFile.cpp",
                "ShpFile.cpp",
                "WsaFile.cpp",
                "Palette.cpp",
                "Animation.cpp",
                "StringFile.cpp",
                "VocFile.cpp",
		"Font.cpp"
              ]

libeastwood = env.SharedLibrary(target='../libeastwood.so', source=all_sources)

Return('libeastwood')

